version: '3.2'

services:
  web:
    platform: linux/amd64
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 5000:5000
    volumes:
    - ./api:/app

  db:
    platform: linux/amd64
    command: --secure-file-priv=/init_data
    build:
      context: ./database
      dockerfile: ./Dockerfile
    healthcheck:
      test: "exit 0"
    ports:
    - 3306:3306
