version: '3.2'

services:
  web:
    platform: linux/amd64
    build:
      context: .
    ports:
    - 5000:5000
    volumes:
    - ./api:/app

  db:
    platform: linux/amd64
    command: --secure-file-priv=/csv
    build:
      context: ./database
      dockerfile: ./Dockerfile
    ports:
    - 3306:3306
