name: Docker Image CI

# Run docker tests on push or pull request on any branch
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker-compose build

    - name: Run the Docker containers
      run: docker-compose up -d
      
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8 - 3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
        
    - name: Run test cases
      run: pytest
      
    - name: Stop Docker containers
      run: docker-compose stop
