# This is a basic workflow to help you get started with Actions

name: Testing

# Run tests on push or pull request on any branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup flask environment
      working-directory: ./api
      run: |
        export FLASK_APP=app
        flask run       
    - name: Run test cases with pytest
      run: |
        pytest
